# Generated by Django 4.1.5 on 2023-01-18 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FlashCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=25)),
                ("answer", models.CharField(max_length=25)),
                ("example", models.CharField(max_length=25)),
            ],
        ),
    ]
