version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - '8000:8000'
    depends_on:
      - db
    container_name: Backend
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
    ports:
      - '5432:5432'
    container_name: Database

volumes:
  postgres_data:
